spring:
  profiles:
    active: dev
    
# 日志配置
logging:
  level:
    io.lettuce.core: WARN
    io.lettuce.core.protocol: WARN
    org.springframework.data.redis: WARN
    cn.dev33.satoken: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"